### PR TITLE
Update contracts used from API endpoint for metric reporting

### PR DESCRIPTION
**Pull request by MSevey**
Since the last time the test app was run we have updated the contract api endpoint.  I think this is all that needed to be updated.

The change is that the fields returned by the API are now `activecontacts`, `inactivecontracts` and `expiredcontracts`.  In order to get the accurate reporting for the current period you need active and inactive contracts.

---
This change is [Reviewable](https://reviewable.io/reviews/mtlynch/sia_metrics_collector/45)

### CODE REVIEW

**Comment by mtlynch** [comment]
Thanks for the PR!

The proposed change currently breaks the repo's unit tests:

https://travis-ci.org/mtlynch/sia_metrics_collector/builds/432683763?utm_source=github_status&utm_medium=notification

Would it be possible to modify the PR so that the unit tests pass?

You can test the build locally by running `./build` in the repo root.

**Comment by MSevey** [comment]
unfortunately I can't seem to get `./build` to work.  I keep getting the following
```
+ SOURCE_DIR=sia_metrics_collector
+ TEST_DIR=tests+ find . -name '*.pyc' -delete
+ coverage run --source sia_metrics_collector -m unittest discover
./build: line 19: coverage: command not found
```

I've tried running `pip install -r requirements.txt` and `pip install -r dev_requirements.txt` but it doesn't seem to be working for me.

**Review by mtlynch — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mtlynch/sia_metrics_collector/45)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @MSevey)

___
*[sia_metrics_collector/state.py, line 121 at r2](https://reviewable.io/reviews/mtlynch/sia_metrics_collector/45#-LNI-xrOBMpqs3yJOCSe:-LNI-xrOBMpqs3yJOCSf:b4qxvqi) ([raw file](https://github.com/mtlynch/sia_metrics_collector/blob/b2e9e79461cdb9801e0dfdf4aa7a071ba0a715ab/sia_metrics_collector/state.py#L121)):*
> ```Python
>             return
>         activeContracts = response[u'activecontracts']
>         inactiveContracts = response[u'inactivecontracts']
> ```

The variable naming in this project is snake_case, so can these be `active_contracts` and `inactive_contracts`?
___
*[sia_metrics_collector/state.py, line 130 at r2](https://reviewable.io/reviews/mtlynch/sia_metrics_collector/45#-LNI0KNQ8GbIJ3oHVZEG:-LNI0KNQ8GbIJ3oHVZEH:b-7uecj6) ([raw file](https://github.com/mtlynch/sia_metrics_collector/blob/b2e9e79461cdb9801e0dfdf4aa7a071ba0a715ab/sia_metrics_collector/state.py#L130)):*
> ```Python
>         state.download_spending = 0
>         state.remaining_renter_funds = 0
>         for contract in activeContracts:
> ```

We can do:

```python
for contract in (active_contracts + inactive_contracts):
   ...
```

And avoid copy/pasting the loop body.
___
*[tests/test_state.py, line 107 at r2](https://reviewable.io/reviews/mtlynch/sia_metrics_collector/45#-LNI0WLP5AZS9ukLb9zB:-LNI0WLP5AZS9ukLb9zC:b-30pk4o) ([raw file](https://github.com/mtlynch/sia_metrics_collector/blob/b2e9e79461cdb9801e0dfdf4aa7a071ba0a715ab/tests/test_state.py#L107)):*
> ```Python
>                     u'size': 77,
>                 },
>             ],
> ```

nit: I prefer not to use exact copies of data in tests. The implementation could count `activecontracts` 2x and ignore `inactivecontracts` and this test would still pass.

Can we modify some of the numbers so that `activecontracts` and `inactivecontracts` are unequal?

(ditto below)

**Comment by mtlynch** [comment]
>unfortunately I can't seem to get `./build` to work. I keep getting the following

Are you on a Linux system? Those are the correct commands to install the `coverage` command.

**Comment by MSevey** [comment]
I addressed your comments.

Yes I'm running linux, not sure why it is being weird for me.

**Comment by mtlynch** [comment]
>I addressed your comments.

Can you fix the [build break](https://travis-ci.org/mtlynch/sia_metrics_collector/builds/433531508?utm_source=github_status&utm_medium=notification)?

>Yes I'm running linux, not sure why it is being weird for me.

If you install Docker, you can run the build locally with `./docker_build` and it will create a Docker container for you that meets all the requirements.

**Comment by MSevey** [comment]
all set

**Review by mtlynch — COMMENTED** [review]
:lgtm: thanks!

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mtlynch/sia_metrics_collector/45#-:-LNMRJoZ5AEO1rBrbcC6:brfqlux)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @mtlynch and @MSevey)

**Review by mtlynch — APPROVED** [review]

**Pull request merged**
